nome = input('Qual seu nome?')
dia = input('Qual seu dia de nascimento?')
mes = input ('Qual seu mes de nascimento?')
ano = input('Qual seu ano de nascimento')
print('Olá',nome,'Voce nasceu no dia',dia,'do mês',mes,'do ano de',ano)
